### PR TITLE
Added notebook, script, and requirements.txt

### PR DESCRIPTION
**Pull request by egrace479**
Added notebook, script, and requirements.txt. Also added run instructions to the README.

### CODE REVIEW

**Comment by hlapp** [comment]
@egrace479 by assigning me and @thompsonmj, did you mean to ask us for review comments? For that, you'd assign us as reviewers. An "Assignee" for a PR would be someone responsible seeing through the PR, such as soliciting reviews, testing, merging, etc.

**Comment by egrace479** [comment]
> @egrace479 by assigning me and @thompsonmj, did you mean to ask us for review comments? For that, you'd assign us as reviewers. An "Assignee" for a PR would be someone responsible seeing through the PR, such as soliciting reviews, testing, merging, etc.

Yes, thank you, that was accidental.

**Review by hlapp — COMMENTED** [review]
My main comment would be whether we can add a little more command-line error checking and flexibility. Specifically, can we check
1. whether there's at least one argument on the command line (otherwise `pd.read_csv()` will probably fail);
2. whether the value of the argument is a file that exists and is readable (again, otherwise `pd.read_csv()` will probably fail);
3. whether parsing the presumed CSV succeeds;
4. whether the resulting dataframe has at least all the required columns;

and output a meaningful error message (as well as stop) at the point where one of the above fails.

For flexibility, it would be nice if either the name of the output file can optionally be supplied over the command line (which the default being what we have), or alternatively that one could choose to output to stdout, which could then be redirected to wherever one wants.

Having said all this, I'm fine with all of this being deemed out of scope for this PR, and being moved to a new issue instead (which would then be addressed in a future PR). I'll leave that choice to you.

**Review by thompsonmj — APPROVED** [review]
`examples/` of input files and output files would be useful! These could also be used for testing later on.

**Comment by egrace479** [comment]
Thanks. I copied both your comments to issues.

**Pull request merged**
