### PR TITLE
Description

### PR DESCRIPTION
**Pull request by egrace479**
Added detailed ReadMe, and added .DS_Store to the .gitignore.

### CODE REVIEW

**Comment by thompsonmj** [comment]
Looks great! It might be helpful to have an `examples/` folder with a corresponding CSV input and JSON output.

**Comment by thompsonmj** [comment]
I'm also a fan of standardized repo names with all lowercase and dashes (`slicermorph-json-generator`), but that's certainly up for debate.

**Comment by thompsonmj** [comment]
We might also use this as an opportunity to decide if we want a repo naming convention. I've seen a lot of resources recommend lowercase with hyphens separating words, so `slicermorph-json-generator` would follow that.

**Comment by hlapp** [comment]
This reminds me of the debates about the merits of camelCase versus underscores in various programming languages. I can see how that matters from a usability end if we're talking about naming in a large public API. But I can't help but think here (naming repositories) and at this point in time for this organization it's a waste of our time.

In fact, putting into place rules and conventions isn't free. They require time and work (discussing, defending, disseminating, training, enforcing, retrofitting, etc), which then can't be spent on other things. There need to be compelling reasons why that work is well spent on rules and conventions, and in this case I'm not seeing them at this time.

**Review by thompsonmj — APPROVED** [review]

**Comment by egrace479** [comment]
`examples/` folder would be a nice touch, and I do agree on the dashes. Thanks!

**Pull request merged**
